# Generated by Django 4.2.4 on 2023-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityName', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=50)),
                ('percentage', models.IntegerField(default=0)),
                ('startYear', models.CharField(default='XXXX', max_length=4)),
                ('endYear', models.CharField(default='XXXX', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=256)),
                ('jobRole', models.CharField(max_length=50)),
                ('startYear', models.CharField(default='XXXX', max_length=4)),
                ('endYear', models.CharField(default='XXXX', max_length=4)),
                ('githubRepo', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('jobRole', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('phoneNo', models.CharField(max_length=13)),
                ('shortSummary', models.TextField()),
                ('latest', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(editable=False, max_length=254)),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Introductions',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('review', models.TextField()),
                ('reviewerName', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=127)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=30)),
                ('expertise', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=50)),
                ('githubRepo', models.URLField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
