# Generated by Django 4.2.4 on 2023-09-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_gender_resume_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='choice',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
    ]
