# Generated by Django 4.2.4 on 2023-09-15 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='other',
        ),
    ]
