# Generated by Django 4.2.4 on 2023-09-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_accounts_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='codechef',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='hackerrank',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='leetcode',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='linkdin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
