# Generated by Django 4.2.4 on 2023-09-15 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_accounts_codechef_alter_accounts_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='latest',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
