# Generated by Django 4.2.4 on 2023-09-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_accounts_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='endYear',
            field=models.CharField(default='XXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='education',
            name='startYear',
            field=models.CharField(default='XXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='endYear',
            field=models.CharField(default='XXXX', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='startYear',
            field=models.CharField(default='XXXX', max_length=20),
        ),
    ]
